version: "3"

services: 

  # immi-link-expo-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: immi-link-expo-service
  #   ports: 
  #     - 8081:8081
  #     - 19000:19000
  #     - 19001:19001
  #     - 19002:19002
  #   volumes:
  #     - ./src:/usr/app
  #     - expo_node_modules:/usr/app/node_modules
  #   env_file:
  #     - .env
  #   restart: always
  #   networks:
  #     - immi-link-network

  immi-link-backend-service:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: immi-link-backend-service
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - backend_node_modules:/usr/app/node_modules
      - ./src/backend:/usr/app
    env_file:
      - .env
    restart: always
    networks:
      - immi-link-network

volumes:
  backend_node_modules:
  expo_node_modules: 

networks:
  immi-link-network:
    external: true